version: '3.7'

# This is the default network driver
# From https://docs.docker.com/network/
# Bridge networks are usually used when your applications run
# in standalone containers that need to communicate
networks:
  app-tier:
    driver: bridge

# services dependencies must be above the dependent
services:
  postgresql-database:
    image: bitnami/postgresql
    networks:
      - app-tier
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=myusername
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=rentx

  app:
    build: .
    networks:
      - app-tier
    container_name: nodejs-rest-api
    ports:
      - 3333:3333
    depends_on:
      - postgresql-database
    volumes:
      - .:/usr/app

volumes:
  postgresql_data:
    driver: local
